# -*- coding: utf-8 -*-
"""exp1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0q2s_kLN2u0d9KZZUDmCLnO6nlWaJu4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Reading the data file
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
#print the datframe
display(df)
#printing the shape
print(df.shape)
#printing top 10 and bottom 10 rows
display(df.head(10))
display(df.tail(10))
#printing the columns
print(df.columns)
#print a feature value
print(df['total_rooms'])
# Selecting one input feature and target feature (dependent) for 150 rows only
X = df['total_rooms'].head(150).values.reshape(-1,1)
y = df['median_house_value'].head(150).values.reshape(-1, 1)

#visualizing these values
plt.scatter(X, y)
plt.xlabel("Total Rooms")
plt.ylabel("Median House Value")
plt.title("Scatter Plot of Total Rooms vs. Median House Value")
plt.show()

#printing the statistical summary
display(df.describe())